version: "3"
services:
  priviblur:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./config.toml:/priviblur/config.toml:Z,ro

  # Taken from https://github.com/zedeus/nitter/blob/b62d73dbd373f08af07c7a79efcd790d3bc1a49c/docker-compose.yml#L27-L44
  priviblur-redis:
    image: redis:6.2-alpine
    container_name: priviblur-redis
    hostname: redis
    command: redis-server --loglevel warning
    volumes:
      - priviblur-redis:/data
    restart: unless-stopped
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  priviblur-redis:
